add_newline = true

command_timeout = 1000

[git_status]
ahead = " ⇡${count}"
diverged = " ⇡${ahead_count}⇣${behind_count}"
modified = "  ${count}"
untracked = "  ${count}"
staged = "  ${count}"
deleted = " 﫧${count}"
conflicted = "  ${count}"
stashed = "  ${count}"
renamed = "  ${count}"

[rlang]
symbol = "R "
